# Configuration for https://pub.dev/packages/build_config
# In general, this file is NOT needed when using go_router_builder
# It is included in this case to suppress lints that are enforced in the source
# repository but not this builder.
targets:
  $default:
    builders:
      go_router_builder:
        options:
          enabled: true
          output: lib/config/routes.g.dart
          input:
            - lib/features/auth/presentation/routes/login_route.dart
            - lib/features/auth/presentation/routes/register_route.dart
      drift_dev:
        options:
          sql:
            dialects: [ sqlite, postgres ]
      json_serializable:
        options:
          explicit_to_json: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - always_specify_types
            - public_member_api_docs