name: firefit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-158.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shadcn_ui:
    git: https://github.com/GQAdonis/flutter-shadcn-ui.git
  hooks_riverpod: ^2.6.1
  core:
    path: ./packages/core
  riverpod_annotation: ^2.6.1
  talker_flutter: ^4.4.3
  dio: ^5.7.0
  envied: ^0.5.4+1
  flutter_markdown: ^0.7.4+1
  reactive_dropdown_search: ^5.0.5
  lottie: ^3.1.3
  http_parser: ^4.1.1
  file_picker: ^8.1.4
  awesome_snackbar_content: ^0.1.4
  equatable: ^2.0.5
  supabase_flutter: ^2.8.0
  reactive_forms: ^17.0.1
  reactive_forms_annotations: ^5.0.0
  flutter_gravatar: ^2.0.2
  flutter_hooks: ^0.20.5
  google_fonts: ^6.2.1
  adaptive_theme: ^3.6.0
  go_router: ^14.6.0
  icons_plus: ^5.0.0
  markdown: ^7.2.2
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_svg: ^2.0.14
  flutter_secure_storage: ^9.0.0
  collection: ^1.19.0
  badges: ^3.1.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  path: ^1.9.0
  fpdart: ^1.1.1
  talker_dio_logger: ^4.4.3
  supabase_auth_ui: ^0.5.4
  uuid: ^4.5.1
  awesome_flutter_extensions: ^1.2.0
  intl: ^0.19.0
  dropdown_search: ^6.0.4-pre
  dropdown_button2: ^3.0.0-beta.19
  carousel_slider: ^5.0.0
  toggle_list: ^0.3.1
  toggle_switch: ^2.3.0
  forui: ^0.6.1
  logging: ^1.3.0
  provider: ^6.1.2
  openai_dart: ^0.4.4
  flutter_highlight: ^0.7.0
  share_plus: ^10.1.2
  path_provider: ^2.1.5
  timeago: ^3.7.0
  loading_animation_widget: ^1.3.0
  flutter_animate: ^4.5.0
  google_nav_bar: ^5.0.7
  graphql: ^5.2.0-beta.9
  graphql_flutter: ^5.2.0-beta.7
  skeletonizer: ^1.4.2

dependency_overrides:
  collection: ^1.19.0
  email_validator: ^3.0.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  melos: ^6.2.0
  riverpod_generator: ^2.6.2
  envied_generator: ^0.5.4+1
  reactive_forms_generator: ^5.0.5
  drift_dev: ^2.21.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: "assets\/fonts\/Inter\/Inter-VariableFont_slnt,wght.ttf"
    - family: OpenSans
      fonts:
        - asset: "assets\/fonts\/Open_Sans\/OpenSans-Italic-VariableFont_wdth,wght.ttf"
        - asset: "assets\/fonts\/Open_Sans\/OpenSans-VariableFont_wdth,wght.ttf"
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist/otf/Geist-Regular.otf
          weight: 400
        - asset: assets/fonts/Geist/otf/Geist-Medium.otf
          weight: 500
        - asset: assets/fonts/Geist/otf/Geist-Bold.otf
          weight: 700
        - asset: assets/fonts/Geist/otf/Geist-Light.otf
          weight: 300
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono/otf/GeistMono-Regular.otf
          weight: 400
        - asset: assets/fonts/GeistMono/otf/GeistMono-Medium.otf
          weight: 500
        - asset: assets/fonts/GeistMono/otf/GeistMono-Bold.otf
          weight: 700
