name: firefit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0-216.1.beta

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shadcn_ui:
    git: https://github.com/nank1ro/flutter-shadcn-ui.git
  hooks_riverpod: ^2.6.1
  core:
    path: ./packages/core
  event_bus: ^2.0.1
  riverpod_annotation: ^2.6.1
  # shared_preferences: ^2.3.2
  talker_flutter: ^4.4.1
  dio: ^5.7.0
  envied: ^0.5.4+1
  flutter_markdown: ^0.7.4+1
  reactive_dropdown_search: ^5.0.4
  lottie: ^3.1.3
  http_parser: ^4.1.1
  file_picker: ^8.1.3
  awesome_snackbar_content: ^0.1.4
  equatable: ^2.0.5
  supabase_flutter: ^2.8.0
  dart_openai: ^5.1.0
  reactive_forms: ^17.0.1
  reactive_forms_annotations: ^5.0.0
  flutter_gravatar: ^2.0.2
  video_player: ^2.9.2
  chewie: ^1.8.5
  flutter_adaptive_scaffold: ^0.3.1
  flutter_hooks: ^0.20.5
  flutter_chat_core: ^0.0.2
  flutter_chat_ui: ^2.0.0-dev.1
  flyer_chat_image_message: ^0.0.2
  flyer_chat_text_message: ^0.0.2
  google_fonts: ^6.2.1
  adaptive_theme: ^3.6.0
  go_router: ^14.3.0
  icons_plus: ^5.0.0
  markdown: ^7.2.2
  image_picker: ^1.1.2
  sembast: ^3.7.5
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_keychain: ^2.5.0
  flutter_svg: ^2.0.10+1
  collection: ^1.19.0
  chat_gpt_flutter: ^1.0.16
  badges: ^3.1.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  path: ^1.9.0
  fpdart: ^1.1.0
  talker_dio_logger: ^4.4.1
  shadcn_flutter: ^0.0.21
  supabase_auth_ui: ^0.5.4
  langchain: ^0.7.7+1
  flutter_lorem: ^2.0.0
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  cross_cache: ^0.0.2
  awesome_flutter_extensions: ^1.2.0
  intl: ^0.19.0
  dropdown_search: ^6.0.4-pre
  dropdown_button2: ^3.0.0-beta.19
  carousel_slider: ^5.0.0
  toggle_list: ^0.3.1
  toggle_switch: ^2.3.0
  web_socket_channel: ^3.0.1
  forui: ^0.6.1
  logging: ^1.3.0

dependency_overrides:
  collection: ^1.19.0
  email_validator: ^3.0.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  melos: ^6.2.0
  riverpod_generator: ^2.6.2
  envied_generator: ^0.5.4+1
  reactive_forms_generator: ^5.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  