# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# Fix for duplicate Contents.json issue
pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
  # Apply Flutter specific settings
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Force all pods to use the minimum iOS version specified by the app
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      
      # Disable Xcode's asset catalog compiler warnings for all pods
      config.build_settings['ASSETCATALOG_COMPILER_WARNINGS'] = 'NO'
      
      # Disable iPad 3x device type for all pods
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
      
      # Add additional build settings to fix iOS 18.4 compatibility issues
      config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      
      # Disable Mac Catalyst and iPad support for all pods
      config.build_settings['SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD'] = 'NO'
      config.build_settings['SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD'] = 'NO'
      config.build_settings['SUPPORTS_MACCATALYST'] = 'NO'
      
      # Completely disable asset catalogs for problematic targets
      if ['StripeUICore', 'DKPhotoGallery', 'StripePaymentsUI', 'StripePayments', 'Stripe'].include?(target.name)
        config.build_settings['ASSETCATALOG_COMPILER_APPICON_NAME'] = ''
        config.build_settings['ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME'] = ''
        config.build_settings['ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME'] = ''
        config.build_settings['ASSETCATALOG_COMPILER_STANDALONE_ICON_BEHAVIOR'] = 'none'
        config.build_settings['ASSETCATALOG_COMPILER_OPTIMIZATION'] = 'space'
        config.build_settings['ASSETCATALOG_COMPILER_SKIP_APP_STORE_DEPLOYMENT'] = 'YES'
        
        # Fix for duplicate Contents.json issue
        config.build_settings['COPY_PHASE_STRIP'] = 'NO'
        config.build_settings['SKIP_INSTALL'] = 'YES'
        
        # Fix for asset catalog issues
        config.build_settings['ASSETCATALOG_COMPILER_NOTICES'] = 'NO'
        config.build_settings['ASSETCATALOG_COMPILER_OPTIMIZATION'] = 'space'
        
        if config.build_settings['OTHER_CFLAGS']
          config.build_settings['OTHER_CFLAGS'] << ' -Wno-error=asset-catalog-compilation'
        else
          config.build_settings['OTHER_CFLAGS'] = '-Wno-error=asset-catalog-compilation'
        end
      end
    end
    
    # Fix for duplicate Contents.json issue
    if ['StripeUICore', 'DKPhotoGallery', 'StripePaymentsUI', 'StripePayments', 'Stripe'].include?(target.name)
      target.build_phases.each do |build_phase|
        if build_phase.respond_to?(:name) && build_phase.name.include?("Copy Bundle Resources")
          build_phase.files_references.each do |file_ref|
            if file_ref && file_ref.path && file_ref.path.include?("Contents.json")
              build_phase.remove_file_reference(file_ref)
            end
          end
        end
      end
      
      # Exclude bundles from the build
      target.build_configurations.each do |config|
        if target.name == 'StripeUICore'
          config.build_settings['EXCLUDED_SOURCE_FILE_NAMES'] = 'StripeUICoreBundle.bundle'
        elsif target.name == 'StripePaymentsUI'
          config.build_settings['EXCLUDED_SOURCE_FILE_NAMES'] = 'StripePaymentsUIBundle.bundle'
        end
      end
    end
  end
  
  # Create a script to completely remove problematic asset catalogs
  script_path = File.join(Dir.pwd, 'fix_asset_catalogs.rb')
  File.open(script_path, 'w') do |file|
    file.puts <<~RUBY
      #!/usr/bin/env ruby
      require 'fileutils'
      
      # Paths to problematic asset catalogs
      problematic_catalogs = [
        File.expand_path('Pods/StripeUICore/StripeUICore/StripeUICore/Resources/StripeUICore.xcassets'),
        File.expand_path('Pods/DKPhotoGallery/DKPhotoGallery/Resource/Resources/Images.xcassets'),
        File.expand_path('Pods/StripePaymentsUI/StripePaymentsUI/StripePaymentsUI/Resources/StripePaymentsUI.xcassets'),
        File.expand_path('Pods/StripePayments/Stripe3DS2/Stripe3DS2/Resources/Stripe3DS2.xcassets'),
        File.expand_path('Pods/Stripe/Stripe/StripeiOS/Resources/StripeiOS.xcassets')
      ]
      
      problematic_catalogs.each do |catalog_path|
        if Dir.exist?(catalog_path)
          puts "Removing problematic asset catalog: \#{catalog_path}"
          
          # Create a backup
          backup_path = "\#{catalog_path}.bak"
          FileUtils.mv(catalog_path, backup_path) if !Dir.exist?(backup_path)
          
          # Create an empty directory structure to replace the asset catalog
          FileUtils.mkdir_p(catalog_path)
          
          # Create an empty Contents.json file
          contents_json = File.join(catalog_path, 'Contents.json')
          File.write(contents_json, '{"info":{"author":"xcode","version":1}}')
          
          puts "  Created empty asset catalog at \#{catalog_path}"
        else
          puts "Asset catalog not found: \#{catalog_path}"
        end
      end
      
      # Also check for any iPad3x assets in other catalogs
      Dir.glob(File.expand_path('Pods/**/*.xcassets/**/*.imageset')).each do |imageset_dir|
        contents_json = File.join(imageset_dir, 'Contents.json')
        if File.exist?(contents_json)
          content = File.read(contents_json)
          if content.include?('ipad') && content.include?('3x')
            puts "Fixing iPad3x references in \#{imageset_dir}"
            
            # Remove iPad3x files
            Dir.glob(File.join(imageset_dir, '*ipad*3x*')).each do |ipad3x_file|
              puts "  Removing file: \#{ipad3x_file}"
              File.delete(ipad3x_file) if File.exist?(ipad3x_file)
            end
            
            # Update Contents.json
            require 'json'
            begin
              json_data = JSON.parse(content)
              if json_data['images']
                json_data['images'].reject! do |img|
                  img['idiom'] == 'ipad' && img['scale'] == '3x'
                end
                File.write(contents_json, JSON.pretty_generate(json_data))
                puts "  Updated Contents.json"
              end
            rescue => e
              puts "  Error processing JSON: \#{e.message}"
            end
          end
        end
      end
      
      # Find and remove all Contents.json files in bundle directories
      Dir.glob(File.expand_path('**/*.bundle/Contents.json')).each do |contents_json|
        puts "Removing bundle Contents.json: \#{contents_json}"
        File.delete(contents_json)
      end
      
      puts "Asset catalog fix completed"
    RUBY
  end
  
  # Make the script executable
  system("chmod +x #{script_path}")
  
  # Run the script
  puts "Running asset catalog fix script..."
  system("ruby #{script_path}")
  
  # Add a build phase to the Runner target to remove Contents.json files during build
  runner_project_path = File.join(Dir.pwd, 'Runner.xcodeproj')
  if File.exist?(runner_project_path)
    puts "Adding build phase to Runner project..."
    
    # Create a script to add the build phase
    build_phase_script_path = File.join(Dir.pwd, 'add_build_phase.rb')
    File.open(build_phase_script_path, 'w') do |file|
      file.puts <<~RUBY
        #!/usr/bin/env ruby
        
        require 'xcodeproj'
        
        def add_build_phase(project_path)
          puts "Adding pre-build phase to \#{project_path}..."
          
          begin
            project = Xcodeproj::Project.open(project_path)
            
            # Find the Runner target
            runner_target = project.targets.find { |t| t.name == 'Runner' }
            
            if runner_target
              puts "Found Runner target"
              
              # Check if the build phase already exists
              existing_phase = runner_target.shell_script_build_phases.find { |phase| phase.name == 'Remove Contents.json' }
              
              if existing_phase
                puts "Updating existing Remove Contents.json build phase"
                existing_phase.shell_script = <<~SCRIPT
                  find "\${BUILT_PRODUCTS_DIR}" -name "*.bundle" -type d -exec find {} -name "Contents.json" \\; | xargs rm -f
                SCRIPT
              else
                puts "Adding new Remove Contents.json build phase"
                new_phase = runner_target.new_shell_script_build_phase('Remove Contents.json')
                new_phase.shell_script = <<~SCRIPT
                  find "\${BUILT_PRODUCTS_DIR}" -name "*.bundle" -type d -exec find {} -name "Contents.json" \\; | xargs rm -f
                SCRIPT
                
                # Move the phase to be the first build phase
                runner_target.build_phases.unshift(runner_target.build_phases.pop)
              end
              
              # Save the project
              project.save
              puts "Successfully added/updated pre-build phase"
            else
              puts "Error: Could not find Runner target"
            end
          rescue => e
            puts "Error adding build phase: \#{e.message}"
            puts e.backtrace
          end
        end
        
        # Add the build phase to Runner.xcodeproj
        add_build_phase("#{runner_project_path}")
      RUBY
    end
    
    # Make the script executable
    system("chmod +x #{build_phase_script_path}")
    
    # Run the script
    puts "Running build phase script..."
    system("ruby #{build_phase_script_path}")
  end
end
